name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gchinaul
          template: classic
          base: header, activity, community, repositories

          # Un rendu "joli" mais pas trop chargé
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Europe/Paris

          # Le fichier généré dans ton repo
          filename: metrics.svg
